### ISSUE TITLE
ボールケースの３Dプリントが出来ない

### ISSUE THREAD

**Issue by bee-tk** [mentako-ya/mtk#12]
以下のファイルを３Dプリントしたいのですが、エラーが発生しておりプリントできません。
https://github.com/mentako-ya/mtk/blob/main/mtk/design/mtk64elp_STL/mtk64_BallCase_RH_rev3_v8.stl

![C-F1W638764A](https://github.com/mentako-ya/mtk/assets/56840401/f5886bba-291e-45b6-9a29-9c8f47f676b3)

すみませんが、プリント可能なファイルを提供していただくことは出来ないでしょうか？

**Comment by mentako-ya** [comment]
エラーが発生しているとのことですが、私の環境（Mac版PrusaSlicer2.5.1)ではエラーを再現できず、STLファイルを再出力しても変わりがありませんでした。
発生しているエラーはどのような内容でしょうか。

スクリーンショットのスライサーが何のスライサーかわからず、エラーの理由がわかりませんが、
画面上にビルドプレートが写っていないようですので、サイズが大きすぎてビルドプレートに収まらないためにエラーになっているのでしょうか。

スライサーによっては、STLファイルを読み込む際の標準のスケールがインチになっているものがあります。
PrusaSlicerの場合、STLファイルをインポートする際に
ファイル＞インポート＞STLのインポートを選ぶと、インポート時のスケールがインチになってしまい、巨大なボールケースになってしまうので、ビルドプレートに収まらず、エラーになります。

PrusaSlicerでミリスケールでSTLをインポートする場合、
ファイル＞インポート＞STL/3MF/STEP/OBJ/AMFのインポートを使用して、ミリ単位でインポートを行う必要があります。

**Comment by bee-tk** [comment]
返信ありがとうございます。手元では再現できないとのこと承知しました。

実はこちらのファイルを3Dプリントするため発注したところから、その図の通りエラーが発生したとの内容のメールのみで詳細のエラー内容も分からないという状況でした…
ただ、stepファイルがあれば解決できるとのことでした。
私自信stlファイルの作成に関する知識が無いため、非常に抽象的な質問となってしまいすみませんでした。

**Comment by mentako-ya** [comment]
画面右下のエラーの明細らしき画面を見ると、一番上の１行目のSurface（mm2）の値が3294になっています
3294平方ミリメートルですと正方形に直すと縦62.6mm✖︎横62.6mmに相当します。
ボールケースのサイズはX 43mm Y 37mm Z 33mm くらいですので、62.6x62.6mmのサイズのSurfaceはありえないと思います。
やはり、STLファイルの読み込みが、インチ単位で行われているのではないでしょうか。
１インチ＝25.4ミリですので、62.6÷25.4=2.46ミリくらいが本来のSurfaceの値なのだと思います。

JLCPCBの3Dプリント https://3d.jlcpcb.com
でSTLファイルをアップロードしたところ、ｍｍ単位で正常にロードできていました。
![スクリーンショット 2023-07-01 7 56 11](https://github.com/mentako-ya/mtk/assets/111166976/02d77ac1-5ed5-4cb2-83f9-d46bcce2c268)

mm単位でファイルをロードするなどロード方法を変えてもらうか、業者を変えてみてはいかがでしょうか。

**Comment by bee-tk** [comment]
なるほどです。
jlcpcbに発注依頼したこともあるのですが、レビュー時に同様のエラーが出て解決してくださいと言われていました。
ロード方法についてmm単位にできないか、相談してみようと思います。

調査いただきありがとうございました。
