### ISSUE TITLE
PMW3389センサーで自動マウスレイヤー切替をオフにしたい時のファームウェアについて

### ISSUE THREAD

**Issue by nakatsu0213** [mentako-ya/mtk#15]
rev2基板
PMW3389センサー
左ロータリーエンコーダー
右ボール用
上記の構成で自動マウスレイヤー切替をオフにしたい場合、mtk_mtk64e_via.hexを導入可能でしょうか？
それとも別途ファームウェアをビルドする必要がありますでしょうか。

**Comment by mentako-ya** [comment]
mtk_mtk64e_via.hexはPMW3360のドライバーを組み込んでいるため、PMW3380では使用できません。
現在のmasterブランチのソースコードから[#define AUTO_MOUSE_LAYER_ENABLE](https://github.com/mentako-ya/mtk/blob/bcf12c0d4c112c3ad22d71f2d6e688836932c6ba/qmk_firmware/keyboards/mtk/mtk64e/keymaps/via/config.h#L38C4-L38C32)の指定を削除してビルドすれば、自動マウスレイヤー切り替え無しのPMW3389版ドライバーがビルドできると思います。（手元に検証できる環境がないため、未確認です）

**Comment by nakatsu0213** [comment]
教えていただいた形でビルドをかけて、ざっくりですが動かしてみた所、こちらの望んだ形で動作しました。
ありがとうございました。
