### ISSUE TITLE
Layer1のマッピングについて

### ISSUE THREAD

**Issue by nakatsu0213** [mentako-ya/mtk#16]
デフォルトのキーマップについて
`レイヤー１:Shiftキー押下相当（大文字入力や記号入力）`
とのことですが、
Layer0の以下2キーのみを変更した時
* MO(0)→Shift
* Layer(1)→全く別の機能

Layer1は使われない認識であっていますでしょうか
(検証してみて、Shift長押しではLayer1を使用せずに大文字や記号が入ることを確認したのですが、念のため私になにか見落としがないかの確認をさせてください。)

**Comment by mentako-ya** [comment]
MO(0)→Shiftに変更する場合、デフォルトのマッピングでLeyer1を使用する必要はありません。
もっとキー数の少ないキーボードで数字キーがないレイアウトでは、Leyer1に数字キー部分のキーをマッピングすると思いますが、本キーボードはキー数が十分にあるので、無理にLeyer1を使用する必要はないと思います。

**Comment by nakatsu0213** [comment]
ご回答ありがとうございました！
