### ISSUE TITLE
RemapのMouse Whが機能しない

### ISSUE THREAD

**Issue by nakatsu0213** [mentako-ya/mtk#17]
ロータリーエンコーダにマウススクロール上下左右を割り当てたくてRemapでMouseWhを割り当てましたが機能しないように見えます

ファームウェアは純正の[mtk_mtk64e_PMW3389_AutoMouseLayer_via.hex](https://raw.githubusercontent.com/mentako-ya/mtk/main/mtk/mtk_mtk64e_PMW3389_AutoMouseLayer_via.hex)を使用しています

**Comment by mentako-ya** [comment]
マウスのホイール操作をキーマップで有効化する場合、MOUSEKEY_ENABLE をyesにしてビルドする必要があります。
ただし、そのままではファームウェアサイズが上限を超えるので、RGBLIGHT_ENABLEをnoにするなど、ファームウェア容量が上限を超えないよう調整が必要です。

https://github.com/mentako-ya/mtk/blob/bcf12c0d4c112c3ad22d71f2d6e688836932c6ba/qmk_firmware/keyboards/mtk/mtk64e/rules.mk#L33

**Comment by nakatsu0213** [comment]
ご回答ありがとうございます。
ここらへんはqmk_firmwareの話っぽいですね、失礼しました。
