### ISSUE TITLE
新ファームウェアでのロータリーエンコーダの挙動について

### ISSUE THREAD

**Issue by nakatsu0213** [mentako-ya/mtk#19]
新仕様Remapに対応いただけたとのことで、ファームウェアを導入して検証してみたところ
ロータリーエンコーダを回したときに発生するキーコードがPageUpかPageDownのいずれかのみになります
ファームウェア導入直後、EEPROMリセット直後、Remap上でそれぞれ上下左右キーを割り振っても、
abcdを割り振っても常に同様です。
（左右どちらのつまみを左に回してもPageUp、右に回してもPageDownになります。
こちらで確認した範囲で押し込み動作は問題ないように見受けられます）

使用したファームウェア類は
mtk_mtk64e_PMW3360_AutoMouseLayer_via.0.22.hex
mtk64e_via.json
で、それぞれ今朝DLしたものになります。

※キーコードの確認は以下で確認しています
https://www.ipentec.com/utils/WebKeyCode/

**Comment by mentako-ya** [comment]
qmk_firmware 0.22ではencoder_update_kbを実装してencoder_update_userをコールする必要があったようです。
以下の修正版ファームウェアをコミットしました
mtk_mtk64e_PMW3360_AutoMouseLayer_via.0.22.hex
mtk_mtk64e_PMW3389_AutoMouseLayer_via.0.22.hex

**Comment by nakatsu0213** [comment]
確認したところ、ロータリエンコーダ周りの不具合は解消されていました。
ご対応ありがとうございました。
