### ISSUE TITLE
無題

### ISSUE THREAD

**Issue by isvc2027i** [mentako-ya/mtk#4]
@mentako-ya 
こんにちは。
先日、メルカリで左右トラックボールの試作品を購入させていただいたものなのですが、
LEDの点灯不良がその後も発生してしまっているため、修理のほうをお願いしたく、
以下アドレスまで、返送先をご連絡お願いできますでしょうか。
よろしくお願いいたします。

**Comment by mentako-ya** [comment]
ご連絡ありがとうございます。
修理品の送付先について、メールにてお送りいたしました。
よろしくお願いいたします。
