### ISSUE TITLE
設定が反映されないキーに関しまして質問です 

### ISSUE THREAD

**Issue by honokani** [mentako-ya/mtk#8]
こんにちは、mtk64eを利用させていただいています。

現状：
* 以下の引用の手順に従って自身でコードを編集しhexファイルを作成・flashしています。
    > ご自身でファームウェアをカスタマイズ、ビルドする場合
    > [via firmware ビルドガイド](https://github.com/mentako-ya/mtk/blob/main/qmk_firmware/keyboards/mtk)

* ほとんど問題なく変更箇所が動作したのですが、以下のキーの設定が反映されません。
    * 左手側キーボードの２つあるロータリーエンコーダのうち左側の、左右回転と押下ボタン
    * 右手側キーボードの親指用の４並んだキーのうち、左から２つ目
* 具体的には[こちら](https://github.com/honokani/mtk/blob/dev_mykey/qmk_firmware/keyboards/mtk/mtk64e/keymaps/via_mykey/keymap.c#L374)のようにコードを修正しています。
（記載のコードはテストのため`KC_A`や`KC_B`、`KC_F`などに変更しています。）
* そのほか
    * ロータリーエンコーダのうち右側は、変更したキーマップを反映・動作できています。
    * トラックボールは問題なく動作しています。

質問内容：
* これらのキーの動作に関して、キーマップを変更する以外に必要な設定はありますでしょうか。
設定すべき項目や、そもそも設定すべき箇所が間違っているなどご教示いただけたらと思います。

**Comment by mentako-ya** [comment]
すみません。こちらのIssuuesを確認しておらず返信遅くなってしまいました。
こちらは解決されていますでしょうか。

修正されていたブランチのソースをビルドして手持ちのキーボードで確認してみると、左手外側のエンコーダーの回転ではcとdが入力されました。
[このコメントアウト](https://github.com/honokani/mtk/blob/dev_mykey/qmk_firmware/keyboards/mtk/mtk64e/keymaps/via_mykey/keymap.c#L416)によりエンコーダーの順序がずれているようですが、コメントアウトを戻せばKC_A ,KC_Bが入力されると思われます。
右手側キーボードの親指用の４並んだキーのうち、左から２つ目はｆが入力されました。

元のファームウェアに入れ替えてみて、キーマップのリセットをしても入力できない場合、物理的な故障で入力ができていないのかもしれません。
キースイッチの変更時のピン折れなども考えられますが、ピンが折れていないのに入力できないキーがある場合や、動作が不安定になっている場合、プロマイクロのコンスルーが抜けかけているかもしれません。
type-c端子に刺したケーブルを上に引っ張ったりすると、コンスルーが抜けてしまいます。
背面のアクリルの穴からプラスネジ二本を外して、プロマイクロのカバーと、OLEDを外してプロマイクロをしっかり基板に押し付けてみてください。

**Comment by honokani** [comment]
いえ、とんでもないです
助かりました！

> [このコメントアウト](https://github.com/honokani/mtk/blob/dev_mykey/qmk_firmware/keyboards/mtk/mtk64e/keymaps/via_mykey/keymap.c#L416)によりエンコーダーの順序がずれているようですが、コメントアウトを戻せばKC_A ,KC_Bが入力されると思われます。

こちらの私の誤りを修正すると、ズレの解消と同時に、意図していた配列で正常動作するようになりました。
余計なコメントアウトをしていた原因はエンコーダ設定とレイヤー数の設定を混同していたためでした…。

お手数おかけいたしました。ありがとうございますm(_ _)m
