### ISSUE TITLE
VIAでvia.jsonファイルが読み込めません

### ISSUE THREAD

**Issue by masatojpn** [mentako-ya/mtk#9]
mtk64eを使わせていただいております。

質問させてください。

VIA(https://usevia.app/) で `mtk64e_via.json` をアップロードすると、添付のようにエラーとなってしまうようです。
![image](https://user-images.githubusercontent.com/38834501/232538163-c4b12bf5-0972-40c8-b90c-9dc305bbcae9.png)

**Comment by mentako-ya** [comment]
mtk64e_via.jsonはremap用に作成されています。
フォーマットが異なるので、そのままではuseviaで使用できません。

ファームウェア自体もremapで使用するためにqmk_firmwareのver.18以前を使用しています。
ver.19以降のqmk_firmwareとはキーコードの互換性がないので、useviaでは一部のキーのマッピングができないと思います。

サリチル酸さんの記事にremapとviaの違い（qmk_firmwareのバージョンの違い）について記載されています。
https://salicylic-acid3.hatenablog.com/entry/via-support
